version: '3.8'

services:
  frontend:
    image: nginx-frontend
    build: 
      context: ./frontend
    ports:
      - "80:80"
    networks: 
      - frontend
      - backend
  
  backend:
    image: nginx-backend
    build:
      context: ./backend
    networks: 
      - backend

networks: 
  frontend:
  backend: