AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  GetConcordance:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::982808228627:role/swagger-lambda'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /analyze
            Method: POST
      Environment:
        Variables:
          sns_topic: 'arn:aws:sns:us-east-1:982808228627:MSCS621_Concordance'
